
development:
  adapter: postgresql
  encoding: unicode
  database: milehigh_development
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: milehigh_test
  pool: 5
  username:
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: milehigh_production
  pool: 5
  username:
  password:
